spring:
  main:
    lazy-initialization: false
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
  datasource:
    platform: postgres

    url: jdbc:postgresql://localhost:5432/cafe
    username: postgres
    password: '74553211'
    #    url: jdbc:postgresql://ec2-52-31-201-170.eu-west-1.compute.amazonaws.com:5432/d2d8d57ghtt4gq
    #    username: jtwicqhtmnwkyw
    #    password: 'c8d17b9e6c8a6e4d7247e675c198337263fd5ef3638736f564f7609e76ec3e23'
    driverClassName: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    encoding: UTF-8
    cache: false
    check-template: true
    check-template-location: true
logging.level.org.springframework.web: info
logging.level.org.hibernate: ERROR
#server:
#  ssl:
#    enabled: true
#    key-store-type: PKCS12
#    key-store: classpath:keystore.p12
#    key-password: 74553211
#    key-alias: tomcat
#    trust-store: classpath:keystore.p12
#    trust-store-password: 74553211
##  port: 80
#  address: 192.168.88.254